spring.application.name=sampleJava

# Oracle DataSources
spring.datasource.url =jdbc:oracle:thin:@//localhost:151/FREEPDB1
spring.datasource.username=study
spring.datasource.password=study1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#히카리 커넥션 풀, DB 연결을 미리 만들어두고, 재사용하기 위한 설정
# HikariCP커넥션 풀
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=3000

# JPA : Java에서 DB 테이블을 객체처럼 다루기 위한 표준 규칙, == .net EntityFramework
# Hibernate: JPA규칙 대로 실제로 동작하는 구현체
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.port=80